[tool.poetry]
name = "bucket3"
version = "0.1.0"
description = ""
authors = ["Zhuoyun Wei"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.34.43"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
